# Generated by Django 4.2.23 on 2025-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço residencial')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
            ],
        ),
    ]
